#!/bin/sh
#
# Execute from the current working directory
#$ -cwd
#
#  This is a long-running job
#$ -l hour
#
#  Can use up to 6GB of memory
#$ -l vf=4G
#
#  Use 4 GPUs
#$ -l gpus=4
#

source /gpfs/data/jhtlab/CSCI2951I/hands/keras_Realtime_Multi-Person_Pose_Estimation/venv/bin/activate

cd /gpfs/data/jhtlab/CSCI2951I/hands/keras_Realtime_Multi-Person_Pose_Estimation/training

python ./train_pose.py train NYU_Hand nyu_hand_short_one
